export const worldCupGames = [
  {
    id: 1,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 3,
    awayTeamId: 4,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Senegal',
    awayTeamEs: 'Países Bajos',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
    matchDay: 1,
  },
  {
    id: 2,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 5,
    awayTeamId: 6,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Inglaterra',
    awayTeamEs: 'Irán',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg',
    matchDay: 1,
  },
  {
    id: 3,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 1,
    awayTeamId: 2,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Qatar',
    awayTeamEs: 'Ecuador',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png',
    matchDay: 1,
  },
  {
    id: 4,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 7,
    awayTeamId: 8,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'U.S.A.',
    awayTeamEs: 'Gales',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Wales_%281959%29.svg/125px-Flag_of_Wales_%281959%29.svg.png',
    matchDay: 1,
  },
  {
    id: 5,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 9,
    awayTeamId: 10,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Argentina',
    awayTeamEs: 'Arabia Saudita',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png',
    matchDay: 2,
  },
  {
    id: 6,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 11,
    awayTeamId: 12,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Dinamarca',
    awayTeamEs: 'Túnez',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png',
    matchDay: 2,
  },
  {
    id: 7,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 13,
    awayTeamId: 14,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'México',
    awayTeamEs: 'Polonia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png',
    matchDay: 2,
  },
  {
    id: 8,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 15,
    awayTeamId: 16,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Francia',
    awayTeamEs: 'Australia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png',
    matchDay: 2,
  },
  {
    id: 9,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 17,
    awayTeamId: 18,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Marruecos',
    awayTeamEs: 'Croacia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
    matchDay: 3,
  },
  {
    id: 10,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 19,
    awayTeamId: 20,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Alemania',
    awayTeamEs: 'Japón',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
    matchDay: 3,
  },
  {
    id: 11,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 21,
    awayTeamId: 22,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'España',
    awayTeamEs: 'Costa Rica',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png',
    matchDay: 3,
  },
  {
    id: 12,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 23,
    awayTeamId: 24,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Bélgica',
    awayTeamEs: 'Canada',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png',
    matchDay: 3,
  },
  {
    id: 13,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 25,
    awayTeamId: 26,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Brasil',
    awayTeamEs: 'Serbia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png',
    matchDay: 4,
  },
  {
    id: 14,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 27,
    awayTeamId: 28,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Portugal',
    awayTeamEs: 'Ghana',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png',
    matchDay: 4,
  },
  {
    id: 15,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 29,
    awayTeamId: 30,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Uruguay',
    awayTeamEs: 'Korea del Sur',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png',
    matchDay: 4,
  },
  {
    id: 16,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 31,
    awayTeamId: 32,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Suiza',
    awayTeamEs: 'Camerún',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png',
    matchDay: 4,
  },
  {
    id: 17,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 6,
    awayTeamId: 8,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Irán',
    awayTeamEs: 'Gales',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Wales_%281959%29.svg/125px-Flag_of_Wales_%281959%29.svg.png',
    matchDay: 5,
  },
  {
    id: 18,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 1,
    awayTeamId: 3,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Qatar',
    awayTeamEs: 'Senegal',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png',
    matchDay: 5,
  },
  {
    id: 19,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 4,
    awayTeamId: 2,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Países Bajos',
    awayTeamEs: 'Ecuador',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png',
    matchDay: 5,
  },
  {
    id: 20,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 5,
    awayTeamId: 7,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Inglaterra',
    awayTeamEs: 'U.S.A.',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png',
    matchDay: 5,
  },
  {
    id: 21,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 12,
    awayTeamId: 16,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Túnez',
    awayTeamEs: 'Australia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png',
    matchDay: 6,
  },
  {
    id: 22,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 14,
    awayTeamId: 10,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Polonia',
    awayTeamEs: 'Arabia Saudita',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png',
    matchDay: 6,
  },
  {
    id: 23,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 15,
    awayTeamId: 11,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Francia',
    awayTeamEs: 'Dinamarca',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png',
    matchDay: 6,
  },
  {
    id: 24,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 9,
    awayTeamId: 13,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Argentina',
    awayTeamEs: 'México',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png',
    matchDay: 6,
  },
  {
    id: 25,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 20,
    awayTeamId: 22,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Japón',
    awayTeamEs: 'Costa Rica',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png',
    matchDay: 7,
  },
  {
    id: 26,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 23,
    awayTeamId: 17,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Bélgica',
    awayTeamEs: 'Marruecos',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
    matchDay: 7,
  },
  {
    id: 27,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 18,
    awayTeamId: 24,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Croacia',
    awayTeamEs: 'Canada',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png',
    matchDay: 7,
  },
  {
    id: 28,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 21,
    awayTeamId: 19,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'España',
    awayTeamEs: 'Alemania',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png',
    matchDay: 7,
  },
  {
    id: 29,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 26,
    awayTeamId: 32,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Serbia',
    awayTeamEs: 'Camerún',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png',
    matchDay: 8,
  },
  {
    id: 30,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 30,
    awayTeamId: 28,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Korea del Sur',
    awayTeamEs: 'Ghana',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png',
    matchDay: 8,
  },
  {
    id: 31,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 25,
    awayTeamId: 31,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Brasil',
    awayTeamEs: 'Suiza',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png',
    matchDay: 8,
  },
  {
    id: 32,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 27,
    awayTeamId: 29,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Portugal',
    awayTeamEs: 'Uruguay',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png',
    matchDay: 8,
  },
  {
    id: 33,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 5,
    awayTeamId: 8,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Inglaterra',
    awayTeamEs: 'Gales',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Wales_%281959%29.svg/125px-Flag_of_Wales_%281959%29.svg.png',
    matchDay: 9,
  },
  {
    id: 34,
    group: 'B',
    gameStatus: 'NOT STARTED',
    homeTeamId: 6,
    awayTeamId: 7,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Irán',
    awayTeamEs: 'U.S.A.',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/c/ca/Flag_of_Iran.svg',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png',
    matchDay: 9,
  },
  {
    id: 35,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 2,
    awayTeamId: 3,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Ecuador',
    awayTeamEs: 'Senegal',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/125px-Flag_of_Ecuador.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png',
    matchDay: 9,
  },
  {
    id: 36,
    group: 'A',
    gameStatus: 'NOT STARTED',
    homeTeamId: 4,
    awayTeamId: 1,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Países Bajos',
    awayTeamEs: 'Qatar',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/125px-Flag_of_Qatar.svg.png',
    matchDay: 9,
  },
  {
    id: 37,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 11,
    awayTeamId: 16,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Dinamarca',
    awayTeamEs: 'Australia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/125px-Flag_of_Denmark.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png',
    matchDay: 10,
  },
  {
    id: 38,
    group: 'D',
    gameStatus: 'NOT STARTED',
    homeTeamId: 12,
    awayTeamId: 15,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Túnez',
    awayTeamEs: 'Francia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/125px-Flag_of_Tunisia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
    matchDay: 10,
  },
  {
    id: 39,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 14,
    awayTeamId: 9,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Polonia',
    awayTeamEs: 'Argentina',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
    matchDay: 10,
  },
  {
    id: 40,
    group: 'C',
    gameStatus: 'NOT STARTED',
    homeTeamId: 10,
    awayTeamId: 13,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Arabia Saudita',
    awayTeamEs: 'México',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/125px-Flag_of_Saudi_Arabia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/125px-Flag_of_Mexico.svg.png',
    matchDay: 10,
  },
  {
    id: 41,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 18,
    awayTeamId: 23,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Croacia',
    awayTeamEs: 'Bélgica',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Belgium.svg/125px-Flag_of_Belgium.svg.png',
    matchDay: 11,
  },
  {
    id: 42,
    group: 'F',
    gameStatus: 'NOT STARTED',
    homeTeamId: 24,
    awayTeamId: 17,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Canada',
    awayTeamEs: 'Marruecos',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Canada_%28Pantone%29.svg/125px-Flag_of_Canada_%28Pantone%29.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
    matchDay: 11,
  },
  {
    id: 43,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 20,
    awayTeamId: 21,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Japón',
    awayTeamEs: 'España',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
    matchDay: 11,
  },
  {
    id: 44,
    group: 'E',
    gameStatus: 'NOT STARTED',
    homeTeamId: 22,
    awayTeamId: 19,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Costa Rica',
    awayTeamEs: 'Alemania',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Costa_Rica_%28state%29.svg/125px-Flag_of_Costa_Rica_%28state%29.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/125px-Flag_of_Germany.svg.png',
    matchDay: 11,
  },
  {
    id: 45,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 28,
    awayTeamId: 29,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Ghana',
    awayTeamEs: 'Uruguay',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/125px-Flag_of_Ghana.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/125px-Flag_of_Uruguay.svg.png',
    matchDay: 12,
  },
  {
    id: 46,
    group: 'G',
    gameStatus: 'NOT STARTED',
    homeTeamId: 30,
    awayTeamId: 27,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Korea del Sur',
    awayTeamEs: 'Portugal',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png',
    matchDay: 12,
  },
  {
    id: 47,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 26,
    awayTeamId: 31,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Serbia',
    awayTeamEs: 'Suiza',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/125px-Flag_of_Serbia.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png',
    matchDay: 12,
  },
  {
    id: 48,
    group: 'H',
    gameStatus: 'NOT STARTED',
    homeTeamId: 25,
    awayTeamId: 32,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Brasil',
    awayTeamEs: 'Camerún',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/125px-Flag_of_Cameroon.svg.png',
    matchDay: 12,
  },
];

export const worldCupGamesBestSixteen = [
  {
    id: 49,
    gameStatus: 'NOT STARTED',
    homeTeamId: 4,
    awayTeamId: 7,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Países Bajos',
    awayTeamEs: 'U.S.A.',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/125px-Flag_of_the_Netherlands.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/125px-Flag_of_the_United_States.svg.png',
    matchDay: 13,
  },
  {
    id: 50,
    gameStatus: 'NOT STARTED',
    homeTeamId: 9,
    awayTeamId: 6,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Argentina',
    awayTeamEs: 'Australia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/125px-Flag_of_Argentina.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/8/88/Flag_of_Australia_%28converted%29.svg/125px-Flag_of_Australia_%28converted%29.svg.png',
    matchDay: 13,
  },
  {
    id: 51,
    gameStatus: 'NOT STARTED',
    homeTeamId: 15,
    awayTeamId: 14,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Francia',
    awayTeamEs: 'Polonia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg/125px-Flag_of_France_%281794%E2%80%931815%2C_1830%E2%80%931974%2C_2020%E2%80%93present%29.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/125px-Flag_of_Poland.svg.png',
    matchDay: 14,
  },
  {
    id: 52,
    gameStatus: 'NOT STARTED',
    homeTeamId: 5,
    awayTeamId: 3,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Inglaterra',
    awayTeamEs: 'Senegal',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Flag_of_England.svg/125px-Flag_of_England.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/125px-Flag_of_Senegal.svg.png',
    matchDay: 14,
  },
  {
    id: 53,
    gameStatus: 'NOT STARTED',
    homeTeamId: 20,
    awayTeamId: 18,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Japón',
    awayTeamEs: 'Croacia',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/125px-Flag_of_Japan.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/125px-Flag_of_Croatia.svg.png',
    matchDay: 15,
  },
  {
    id: 54,
    gameStatus: 'NOT STARTED',
    homeTeamId: 25,
    awayTeamId: 30,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Brasil',
    awayTeamEs: 'Korea del Sur',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/125px-Flag_of_Brazil.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/125px-Flag_of_South_Korea.svg.png',
    matchDay: 15,
  },
  {
    id: 55,
    gameStatus: 'NOT STARTED',
    homeTeamId: 17,
    awayTeamId: 21,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Marruecos',
    awayTeamEs: 'España',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/125px-Flag_of_Morocco.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/125px-Flag_of_Spain.svg.png',
    matchDay: 16,
  },
  {
    id: 56,
    gameStatus: 'NOT STARTED',
    homeTeamId: 27,
    awayTeamId: 31,
    homeScore: 0,
    awayScore: 0,
    homeTeamEs: 'Portugal',
    awayTeamEs: 'Suiza',
    homeFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/125px-Flag_of_Portugal.svg.png',
    awayFlag:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Switzerland.svg/100px-Flag_of_Switzerland.svg.png',
    matchDay: 16,
  },
];
